# Generated by Django 5.2.10 on 2026-01-26 00:04

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.CharField(blank=True, max_length=250)),
                ('body_richtext', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('image', 5), ('gallery', 10), ('embed', 11), ('code', 14), ('table', 15), ('callout', 18), ('button', 22), ('divider', 23), ('spacer', 25), ('section', 28)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote', 'code', 'image', 'embed']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('content', 'Content width'), ('wide', 'Wide'), ('full', 'Full width')]}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('center', 'Center'), ('left', 'Float left'), ('right', 'Float right')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('credit', 2), ('width', 3), ('align', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.ListBlock', (7,), {'max_num': 12, 'min_num': 2}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 columns'), ('3', '3 columns'), ('4', '4 columns')]}), 10: ('wagtail.blocks.StructBlock', [[('title', 6), ('images', 8), ('columns', 9)]], {}), 11: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Plain text'), ('python', 'Python'), ('bash', 'Bash'), ('json', 'JSON'), ('yaml', 'YAML'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('sql', 'SQL')]}), 13: ('wagtail.blocks.TextBlock', (), {'required': True, 'rows': 10}), 14: ('wagtail.blocks.StructBlock', [[('language', 12), ('code', 13)]], {}), 15: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')]}), 17: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 18: ('wagtail.blocks.StructBlock', [[('style', 16), ('title', 6), ('text', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 40}), 20: ('wagtail.blocks.URLBlock', (), {}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('outline', 'Outline'), ('link', 'Link')]}), 22: ('wagtail.blocks.StructBlock', [[('text', 19), ('url', 20), ('variant', 21)]], {}), 23: ('wagtail.blocks.StructBlock', [[]], {}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')]}), 25: ('wagtail.blocks.StructBlock', [[('size', 24)]], {}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('soft', 'Soft surface'), ('contrast', 'Contrast surface')]}), 27: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 5), ('gallery', 10), ('embed', 11), ('code', 14), ('table', 15), ('callout', 18), ('button', 22), ('divider', 23), ('spacer', 25)]], {'blank': True, 'use_json_field': True}), 28: ('wagtail.blocks.StructBlock', [[('background', 26), ('inner', 27)]], {})})),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cms.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
