# Generated by Django 5.2.10 on 2026-01-26 00:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='body_richtext',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('quote', 6), ('embed', 7), ('callout', 10), ('code', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote', 'code'], 'icon': 'doc-full'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('center', 'Center'), ('wide', 'Wide'), ('full', 'Full width'), ('left', 'Left (wrap)'), ('right', 'Right (wrap)')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('alignment', 4)]], {'icon': 'image', 'label': 'Image'}), 6: ('wagtail.blocks.BlockQuoteBlock', (), {'icon': 'openquote'}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('tip', 'Tip'), ('warn', 'Warning'), ('note', 'Note')]}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 10: ('wagtail.blocks.StructBlock', [[('style', 8), ('title', 3), ('text', 9)]], {'icon': 'placeholder', 'label': 'Callout'}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: filename or label', 'required': False}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('bash', 'Bash'), ('json', 'JSON'), ('yaml', 'YAML'), ('sql', 'SQL'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('r', 'R'), ('text', 'Plain text')]}), 13: ('wagtail.blocks.TextBlock', (), {'rows': 12}), 14: ('wagtail.blocks.StructBlock', [[('title', 11), ('language', 12), ('code', 13)]], {'icon': 'code', 'label': 'Code block'})}),
        ),
    ]
