# Generated by Django 5.2.10 on 2026-01-26 00:24

import django.db.models.deletion
import modelcluster.contrib.taggit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_blogpage_body_richtext_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Blog post'},
        ),
        migrations.AddField(
            model_name='blogpage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark as featured (useful for homepage / blog index highlights).'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='hero_caption',
            field=models.CharField(blank=True, help_text='Optional caption under the hero image.', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Optional header image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='reading_time_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional: show an estimated read time (minutes).', null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
