# Generated by Django 6.0.1 on 2026-05-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_blogpage_body_alter_portfolioprojectpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Post date'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark as featured (useful for homepage / blog index highlights).'),
        ),
    ]
