# Generated by Django 5.2.15 on 2026-06-19 09:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_migrate_paragraph_to_aligned'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sections',
            field=wagtail.fields.StreamField([('about', 1), ('skills', 2), ('timeline', 3), ('work', 4), ('research', 5), ('contact', 6), ('gallery', 13), ('carousel', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional heading override (defaults to the standard title).', 'max_length': 120, 'required': False}), 1: ('wagtail.blocks.StructBlock', [[('title', 0)]], {'icon': 'user', 'label': 'About'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0)]], {'icon': 'cog', 'label': 'Skills'}), 3: ('wagtail.blocks.StructBlock', [[('title', 0)]], {'icon': 'list-ul', 'label': 'Timeline'}), 4: ('wagtail.blocks.StructBlock', [[('title', 0)]], {'icon': 'folder-open-inverse', 'label': 'Work / Projects'}), 5: ('wagtail.blocks.StructBlock', [[('title', 0)]], {'icon': 'doc-full', 'label': 'Research / Publications'}), 6: ('wagtail.blocks.StructBlock', [[('title', 0)]], {'icon': 'mail', 'label': 'Contact'}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Gallery', 'max_length': 120, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 240, 'required': False}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('image', 9), ('caption', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 7), ('intro', 8), ('items', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 15: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Auto-advance every 5 seconds.', 'required': False}), 16: ('wagtail.blocks.URLBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('image', 9), ('caption', 10), ('link', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 14), ('intro', 8), ('autoplay', 15), ('slides', 18)]], {})}, help_text='The homepage sections, in order. Add/remove sections to control what shows and the navbar; gallery and carousel stay out of the nav.'),
        ),
    ]
