# Generated by Django 6.0.1 on 2026-06-19 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_blogpage_body_alter_portfolioprojectpage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='card_image',
            field=models.ForeignKey(blank=True, help_text='Thumbnail shown on the blog index card. Falls back to the hero image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='portfolioprojectpage',
            name='card_image',
            field=models.ForeignKey(blank=True, help_text='Square thumbnail shown on the work list. Falls back to the cover image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
