# Generated by Django 6.0.1 on 2026-06-19 22:43

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_blogpage_card_image_portfolioprojectpage_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioprojectpage',
            name='approach',
            field=wagtail.fields.RichTextField(blank=True, help_text='How you tackled it.'),
        ),
        migrations.AddField(
            model_name='portfolioprojectpage',
            name='date',
            field=models.DateField(blank=True, db_index=True, help_text='Used to order projects and drive prev/next navigation.', null=True, verbose_name='Project date'),
        ),
        migrations.AddField(
            model_name='portfolioprojectpage',
            name='outcome',
            field=wagtail.fields.RichTextField(blank=True, help_text='The result / impact.'),
        ),
        migrations.AddField(
            model_name='portfolioprojectpage',
            name='problem',
            field=wagtail.fields.RichTextField(blank=True, help_text='The challenge / context.'),
        ),
        migrations.AddField(
            model_name='portfolioprojectpage',
            name='result_metric',
            field=models.CharField(blank=True, help_text='One-line headline result, e.g. "3.2× faster variant calls".', max_length=120),
        ),
        migrations.AddField(
            model_name='portfolioprojectpage',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma-separated tech chips, e.g. Nextflow, Python, Postgres.', max_length=300),
        ),
    ]
