# Generated by Django 5.2.8 on 2025-11-11 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('level', models.PositiveSmallIntegerField(help_text='0–100 (used only for bar width; percentages are not shown).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, help_text="Optional Bootstrap Icon class (e.g., 'bi-code-slash').", max_length=64)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SiteCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('about_title', 'About: Section Title'), ('about_lead', 'About: Lead Paragraph'), ('about_intro_headline', 'About: Intro Headline'), ('about_intro_body', 'About: Intro Body'), ('skills_title', 'Skills: Section Title'), ('skills_lead', 'Skills: Lead Paragraph'), ('about_quote', 'About: Quote')], db_index=True, max_length=64)),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Site Copy',
                'indexes': [models.Index(fields=['key', 'active'], name='main_siteco_key_2ba893_idx')],
            },
        ),
    ]
