# Generated by Django 5.2.8 on 2025-11-11 17:27

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_portfoliocategory_portfoliopage_portfolioitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='tags_csv',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Select one or more categories (these are your tags).', related_name='items', to='main.portfoliocategory'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to=main.models.portfolio_upload_to),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='lightbox_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.portfolio_upload_to),
        ),
    ]
