# Generated by Django 5.2.8 on 2025-11-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_portfolioitem_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioPage',
        ),
    ]
