# Generated by Django 5.2.8 on 2025-11-11 17:38

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_portfoliopage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('about_profile', 'About: Profile Image')], db_index=True, max_length=64)),
                ('image', models.ImageField(upload_to=main.models.site_upload_to)),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Asset',
                'verbose_name_plural': 'Site Assets',
                'indexes': [models.Index(fields=['key', 'active'], name='main_siteas_key_12e9e6_idx')],
            },
        ),
    ]
