# Generated by Django 5.2.8 on 2025-11-11 18:18

import main.models
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_siteasset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ('order', 'id')},
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='body_md',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='hero',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_portfolio_img),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='items', to='main.portfoliocategory'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to=main.models.upload_portfolio_img),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='lightbox_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_portfolio_img),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='key',
            field=models.CharField(choices=[('about_profile', 'About: Profile Image'), ('home_profile', 'About: Home Image')], db_index=True, max_length=64),
        ),
    ]
