# Generated by Django 5.2.10 on 2026-01-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_portfolioitem_body_md_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='categories',
        ),
        migrations.DeleteModel(
            name='PortfolioCategory',
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
