# Generated by Django 5.2.14 on 2026-05-12 19:59

import main.models
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_portfolioitem_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteasset',
            name='image',
            field=models.ImageField(upload_to=main.models.site_upload_to, validators=[main.validators.validate_image_file]),
        ),
    ]
