# Generated by Django 6.0.1 on 2026-05-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_siteasset_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', '-start_year'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education entries'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', '-start_year'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experience entries'},
        ),
        migrations.AlterModelOptions(
            name='experiencebullet',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Experience bullet', 'verbose_name_plural': 'Experience bullets'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
