# Generated by Django 6.0.1 on 2026-05-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_education_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(help_text="Author list as displayed, e.g. 'Correia R, Smith J, Jones A'.")),
                ('highlight_name', models.CharField(blank=True, help_text='Your name as it appears in authors — will be bolded in the CV.', max_length=100)),
                ('venue', models.CharField(help_text='Journal or conference name.', max_length=300)),
                ('year', models.PositiveIntegerField()),
                ('pub_type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('preprint', 'Preprint'), ('thesis', 'Thesis / Dissertation'), ('book_chapter', 'Book Chapter'), ('other', 'Other')], default='journal', max_length=20)),
                ('doi', models.CharField(blank=True, max_length=150)),
                ('url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('orcid_put_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('citation_count', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-year', 'order', 'id'],
            },
        ),
    ]
