# Generated by Django 6.0.1 on 2026-05-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('issuer', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Award / Honour',
                'verbose_name_plural': 'Awards & Honours',
                'ordering': ['-year', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('funder', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, help_text='e.g. Principal Investigator, Co-Investigator.', max_length=100)),
                ('amount', models.CharField(blank=True, help_text='e.g. €50,000', max_length=60)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('orcid_put_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grants',
                'ordering': ['-start_year', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('level', models.CharField(choices=[('native', 'Native'), ('fluent', 'Fluent'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('basic', 'Basic')], default='fluent', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['order', 'id'],
            },
        ),
    ]
