# Generated by Django 5.2.15 on 2026-06-18 23:36

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_grant_award_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencebullet',
            name='experience',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='main.experience'),
        ),
    ]
