# Generated by Django 5.2.15 on 2026-06-18 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_experiencebullet_experience'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(blank=True, default='About', max_length=200)),
                ('about_lead', models.TextField(blank=True)),
                ('about_intro_headline', models.CharField(blank=True, max_length=300)),
                ('about_intro_body', models.TextField(blank=True)),
                ('about_quote', models.TextField(blank=True)),
                ('skills_title', models.CharField(blank=True, default='Skills', max_length=200)),
                ('skills_lead', models.TextField(blank=True)),
                ('about_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('home_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Site content',
            },
        ),
    ]
