# Generated by Django 5.2.15 on 2026-06-18 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_migrate_sitecopy_siteasset_to_sitecontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteAsset',
        ),
        migrations.DeleteModel(
            name='SiteCopy',
        ),
    ]
