# Generated by Django 5.2.15 on 2026-06-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_siteasset_delete_sitecopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='github_username',
            field=models.CharField(blank=True, help_text='GitHub username, used to show live repo/stars stats.', max_length=100),
        ),
    ]
