# Generated by Django 5.2.15 on 2026-06-19 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_sitecontent_github_username'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='cv_document',
            field=models.ForeignKey(blank=True, help_text='Auto-generated CV PDF. Managed automatically — no need to set this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='cv_enabled',
            field=models.BooleanField(default=True, help_text="Show the 'Open CV' button on the site."),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='cv_generated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='cv_refresh',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', help_text='How often the CV PDF is regenerated from your CMS data.', max_length=10),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='email',
            field=models.EmailField(blank=True, default='rafaelmdcorreia@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='full_name',
            field=models.CharField(blank=True, default='Rafael Correia', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com/in/rafael-alexandre-correia-2b8a33213'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='role_title',
            field=models.CharField(blank=True, default='Software Developer & Researcher', help_text='Headline role, shown on the CV.', max_length=160),
        ),
    ]
