# Generated by Django 5.2.15 on 2026-06-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_sitecontent_cv_document_sitecontent_cv_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_focus',
            field=models.CharField(blank=True, default='bioinformatics · genomics', help_text="Value shown for the 'focus' row.", max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_headline',
            field=models.CharField(blank=True, default="Let's turn biology into something runnable.", max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_note',
            field=models.CharField(blank=True, default='always happy to talk research, code, or collaboration', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_show_blog',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_show_github',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_show_linkedin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_cta_primary',
            field=models.CharField(blank=True, default='View selected work', max_length=60),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_cta_secondary',
            field=models.CharField(blank=True, default='Timeline & CV', max_length=60),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='MSc Bioinformatics · biology ∩ data', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_headline',
            field=models.CharField(blank=True, default='I turn biological questions into reproducible code.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_highlight',
            field=models.CharField(blank=True, default='reproducible code.', help_text='Part of the headline to highlight (must appear in the headline).', max_length=100),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stat_commits',
            field=models.BooleanField(default=True, verbose_name='Show commits'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stat_focus',
            field=models.BooleanField(default=True, verbose_name='Show focus'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stat_followers',
            field=models.BooleanField(default=False, verbose_name='Show followers'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stat_honors',
            field=models.BooleanField(default=False, verbose_name='Show honors'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stat_language',
            field=models.BooleanField(default=True, verbose_name='Show top language'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stat_publications',
            field=models.BooleanField(default=True, verbose_name='Show publications'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stat_repos',
            field=models.BooleanField(default=False, verbose_name='Show public repos'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stat_stars',
            field=models.BooleanField(default=True, verbose_name='Show total stars'),
        ),
    ]
