# Generated by Django 6.0.1 on 2026-06-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_sitecontent_about_focus_sitecontent_contact_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='building_since',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Year you started building/coding. Shown as a 'building since' row.", null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='current_status',
            field=models.CharField(blank=True, help_text="Short status line, e.g. 'MSc Bioinformatics @ NOVA'. Shown as 'currently'.", max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='primary_domain',
            field=models.CharField(blank=True, help_text="Your main field, e.g. 'genomics · pipelines'. Shown as 'domain'.", max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stat_building',
            field=models.BooleanField(default=True, verbose_name="Show 'building since'"),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stat_domain',
            field=models.BooleanField(default=False, verbose_name='Show primary domain'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stat_projects',
            field=models.BooleanField(default=True, verbose_name='Show projects shipped'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stat_status',
            field=models.BooleanField(default=True, verbose_name='Show current status'),
        ),
    ]
