# Generated by Django 6.0.1 on 2026-06-19 22:43

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_sitecontent_building_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='uses',
            field=wagtail.fields.StreamField([('category', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Editor, Bioinformatics, Homelab.'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Tool / app / piece of gear.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional short note.', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link.', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 1), ('detail', 2), ('url', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 5)]], {})}, help_text='Tools/gear grouped by category, shown on /uses.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='uses_intro',
            field=models.CharField(blank=True, help_text='Short intro line for the /uses page.', max_length=250),
        ),
    ]
