import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { getBlogPost, getBlogPosts, getSiteBundle, adjacent, related } from "@/lib/api";
import BlogPostView from "@/components/views/BlogPostView";
import JsonLd from "@/components/JsonLd";
import { articleLd, breadcrumbLd } from "@/lib/jsonld";

export const dynamic = "force-dynamic";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const post = await getBlogPost(slug);
  if (!post) return {};
  // OG/Twitter image is generated by the colocated opengraph-image.tsx.
  return {
    title: `${post.title} — Rafael Correia`,
    description: post.intro || undefined,
    openGraph: {
      type: "article",
      title: post.title,
      description: post.intro || undefined,
      url: `/blog/${slug}`,
    },
    twitter: { card: "summary_large_image" },
  };
}

export default async function BlogPost({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const [post, list, bundle] = await Promise.all([
    getBlogPost(slug),
    getBlogPosts(),
    getSiteBundle(),
  ]);
  if (!post) notFound();

  const nav = adjacent(list, slug);
  const rel = related(list, post);

  return (
    <>
      <JsonLd
        data={[
          articleLd(post, bundle),
          breadcrumbLd([
            ["Home", "/"],
            ["Blog", "/blog"],
            [post.title, `/blog/${slug}`],
          ]),
        ]}
      />
      <BlogPostView post={post} prev={nav.prev} next={nav.next} related={rel} />
    </>
  );
}
