import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { getProject, getProjects, getSiteBundle, adjacent, related } from "@/lib/api";
import ProjectView from "@/components/views/ProjectView";
import JsonLd from "@/components/JsonLd";
import { creativeWorkLd, breadcrumbLd } from "@/lib/jsonld";

export const dynamic = "force-dynamic";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const project = await getProject(slug);
  if (!project) return {};
  // OG/Twitter image is generated by the colocated opengraph-image.tsx.
  return {
    title: `${project.title} — Rafael Correia`,
    description: project.subtitle || undefined,
    openGraph: {
      type: "article",
      title: project.title,
      description: project.subtitle || undefined,
      url: `/portfolio/${slug}`,
    },
    twitter: { card: "summary_large_image" },
  };
}

export default async function ProjectPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const [project, list, bundle] = await Promise.all([
    getProject(slug),
    getProjects(),
    getSiteBundle(),
  ]);
  if (!project) notFound();

  const nav = adjacent(list, slug);
  const rel = related(list, project);

  return (
    <>
      <JsonLd
        data={[
          creativeWorkLd(project, bundle),
          breadcrumbLd([
            ["Home", "/"],
            ["Work", "/#work"],
            [project.title, `/portfolio/${slug}`],
          ]),
        ]}
      />
      <ProjectView project={project} prev={nav.prev} next={nav.next} related={rel} />
    </>
  );
}
